
version: 2
sources:
    - name: datafeed_shared_schema
      database:  "{{('dbt_db')}}"
      schema: stage_layer
      tables:
            
           - name: stg_customer_data
           - name: stg_payments 
           - name: stg_order
